# Generated by Django 2.2.5 on 2021-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream_App', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
