# Generated by Django 2.2.5 on 2021-02-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stream_App', '0003_auto_20210216_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('image', models.ImageField(upload_to='categories_image')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, related_name='video_category', to='Stream_App.Category'),
            preserve_default=False,
        ),
    ]
