# Generated by Django 2.2.5 on 2021-02-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stream_App', '0004_auto_20210220_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_category', to='Stream_App.Category'),
        ),
    ]
